import {TaskType} from "./store/tasks/tasks-types";

export const TASKS_INITIAL_CONST_STATE: TaskType[] = [
    {
      id: 0,
      title: 'Test Task 1',
      description: 'Description',
      creationTime: '2023-04-07T06:15:39.874Z',
      priority: 'Low',
      marks: ['research'],
    },
    {
        id: 1,
        title: 'Test Task 2',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Normal',
        marks: ['research'],
    },
    {
        id: 2,
        title: 'Test Task 3',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'High',
        marks: ['research', "design", "development"],
    },
    {
        id: 3,
        title: 'Test Task 4',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'High',
        marks: [],
    },
    {
        id: 4,
        title: 'Test Task 5',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 5,
        title: 'Test Task 6',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 6,
        title: 'Test Task 7',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 7,
        title: 'Test Task 8',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 8,
        title: 'Test Task 9',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 9,
        title: 'Test Task 10',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 10,
        title: 'Test Task 11',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 11,
        title: 'Test Task 12',
        description: 'Description',
        creationTime: '2023-04-07T02:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 12,
        title: 'Test Task 13',
        description: 'Description',
        creationTime: '2023-04-07T01:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 13,
        title: 'Test Task 14',
        description: 'Description',
        creationTime: '2023-04-04T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 14,
        title: 'Test Task 15',
        description: 'Description',
        creationTime: '2023-04-05T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 15,
        title: 'Test Task 16',
        description: 'Description',
        creationTime: '2023-02-02T06:15:39.874Z',
        priority: 'Low',
        marks: ['research'],
    },
    {
        id: 16,
        title: 'Test Task 17',
        description: 'Description',
        creationTime: '1977-04-07T06:15:39.874Z',
        priority: 'Normal',
        marks: ['research'],
    },
    {
        id: 17,
        title: 'Test Task 18',
        description: 'Description',
        creationTime: '2023-04-07T06:15:39.874Z',
        priority: 'High',
        marks: ['research', "design"],
    },
]
